name: merapi-api-etl

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 apscheduler pytz

      - name: Run ETL
        run: |
          python transform.py
      
      - name: Deploy data.json to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: ./
            destination_dir: .
            keep_files: false
            enable_jekyll: false
            exclude_assets: |
              fetch.py
              raw.py
              schedule.py
              show.py
              transform.py
              README.md
              LICENSE
              .gitignore